version: 2
jobs:
  build:
    docker:
     # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
       # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
        # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.13/2022-10-31/bin/linux/amd64/kubectl
            chmod +x kubectl 
            mv kubectl /usr/local/bin
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
      - save_cache:    
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  # run lint!
  lint: 
    docker:
      - image: python:3.7.3-stretch
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

workflows:
  default:
    jobs:
      - build
      - lint
          requires: [build]
